export const COPY = {
  authPrompt:
    "Connect to Kaskama. This only identifies your wallet. No KAS will be sent.",
  kaswareMissing: "Kasware extension not found.",
  kaswareDownload: "Get Kasware",
  getKas: "Get KAS",
  wrongNetwork: "Your wallet is on the wrong network. Switch networks and try again.",
  networkSwitched: "You're on {network} now.",
  walletCancelled: "Wallet connection cancelled.",
  signInCancelled: "Sign-in cancelled.",
  verificationFailed: "Kaskama could not verify this wallet. Try again.",
  serverDown: "Server is down. Try again shortly.",
  uploadFailed: "Couldn't add it. Try again.",
  invalidPrice: "Enter a KAS price of zero or more, using up to 8 decimal places.",
  permanence:
    "You can't edit a post once it's published. You can delete it later, but fans who unlocked it may keep a copy.",
  publishingCancelled: "Publishing cancelled.",
  publishing: "Publishing...",
  published: "Published.",
  publishFailed: "Post was not published. Try again.",
  mediaAlreadyPublished: "You've already published this.",
  mediaUnavailable:
    "This media is temporarily unavailable. Your purchase is unchanged.",
  unlockPrompt:
    "You are supporting this creator with {price} KAS. Kasware will show the network fee before you approve. This payment cannot be reversed.",
  paymentCancelled: "Payment cancelled.",
  unlocked: "Unlocked.",
  insufficientFunds: "You'll need some KAS to pay for this.",
  transactionRejected: "Transaction rejected. Nothing was charged. Try again.",
  purchasePending: "Purchase pending. Do not pay again.",
  paymentTimedOut:
    "We couldn't confirm the payment. Check the transaction and try again.",
  accessVerificationFailed:
    "Kaskama can't verify your subscription right now. Try again.",
  unlockRequired: "Unlock this post to view it.",
  feedbackButton: "Feedback",
  feedbackDialogTitle: "Send feedback",
  feedbackLabel: "Feedback or content report",
  feedbackHint: "Anonymous",
  feedbackPlaceholder: "Tell us what happened or what we can improve",
  feedbackSend: "Send",
  feedbackThanks: "Thanks - sent.",
  feedbackRequired: "Write a few words first.",
  feedbackFailed: "Couldn’t send feedback. Try again.",
  shareButton: "Share",
  shareTitle: "Copy a link. You earn when someone buys through it.",
  shareCopied: "Share link copied. You earn when someone buys through it.",
  linkCopied: "Link copied.",
  shareFailed: "Couldn't copy the link.",
  checkoutKicker: "Subscription",
  checkoutSubscribe: "Subscribe",
  checkoutPreparing: "Preparing...",
  checkoutConfirming: "Confirming...",
  checkoutCopyLink: "Copy checkout link",
  checkoutLinkCopied: "Checkout link copied.",
  checkoutLinkLabel: "Checkout page",
  checkoutPreview:
    "This is your checkout page. Share this link so readers can subscribe.",
  checkoutSellerMissing: "This seller isn't available.",
  checkoutUnavailable: "This merchant hasn't set up checkout yet.",
  checkoutSubscriptionUnavailable:
    "This merchant's subscription isn't available right now.",
  checkoutOfferNotServiceable: "Your subscription isn't available right now.",
  checkoutOfferNotServiceableNote:
    "Kaskama can't verify it on-chain yet, so checkout is paused.",
  checkoutStartHint: "Set your price",
  checkoutStart: "Start subscription",
  checkoutUpdatePrice: "Update price",
  checkoutPriceLabel: "Monthly subscription price in KAS",
  checkoutPaymentFailed: "Payment failed. Nothing was charged.",
} as const;
